name: ci-workflow
on:
  push:
    branches:
        - develop
  pull_request:
    branches:
        - develop
jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: Welcome Step
        run: echo "wecome to GitHub Actions"
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Repository Basic Info
        run: | 
          echo "Reopository Name: ${{github.repository}}"
          echo "Repository Owner: ${{github.owner}}"
          echo "Event NAME: ${{github.event}}"